name: functions_framework_tool
description: >
  A CLI for your FaaS (Function as a service) portable Dart functions projects
# After changing the version, run `pub run build_runner build`.
version: 0.2.0
homepage: https://github.com/GoogleCloudPlatform/functions-framework-dart

environment:
  sdk: '>=2.10.0 <3.0.0'

executables:
  gfn:

dependencies:
  args: ^1.6.0
  path: ^1.7.0
  pedantic: ^1.9.2
  stagehand: ^3.3.11
  usage: ^3.4.2

dev_dependencies:
  build: ^1.5.2
  build_config: ^0.4.5
  build_runner: ^1.10.9
  build_version: ^2.0.1
  glob: ^1.2.0
  grinder: ^0.8.6
  source_gen: ^0.9.10
  test: ^1.15.7
  yaml: ^2.2.1
